// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskFlow.Data;

#nullable disable

namespace TaskFlow.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251228190000_AddStanZatrudnieniaField")]
    partial class AddStanZatrudnieniaField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TaskFlow.Models.Pracownik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Firma")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmaId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Informacje")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LiczbaDniNaZadanie")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LiczbaDniNaZeszycie")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LiczbaDniWolnych")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LiczbaDniWykorzystanych")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MPK")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NrPrzepustki")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SEPNapiecie")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SEPNr")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SEPWazneDo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stanowisko")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("StawkaZlH")
                        .HasColumnType("TEXT");

                    b.Property<string>("StanZatrudnienia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypPracownika")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pracownicy");
                });

#pragma warning restore 612, 618
        }
    }
}
